name: 'Setup DevOps Tools'
description: 'Instala y configura kubectl y helm en el runner de forma dinamica'

runs:
  using: "composite"
  steps:
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'